name: ESLint

on: [push, pull_request]

permissions: read-all

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Setup node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.4.1
        with:
          node-version: 16

      - name: Run ESLint
        run: |
          npm ci
          npx eslint . --format @microsoft/eslint-formatter-sarif --output-file build/eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@86f3159a697a097a813ad9bfa0002412d97690a4 # tag=v2.1.25
        with:
          sarif_file: build/eslint-results.sarif
          wait-for-processing: true
