name: ESLint

on: [push, pull_request]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run ESLint
        run: |
          npm ci
          npx eslint . --format @microsoft/eslint-formatter-sarif --output-file build/eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: build/eslint-results.sarif
          wait-for-processing: true
