name: Jest

on: push

permissions: read-all

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v4.2.2

      - name: Setup node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # tag=v4.2.0
        with:
          node-version: 18

      - name: Run tests
        run: |
          npm ci
          npx lerna run prepack
          npm run test-ci
        env:
          TZ: America/Toronto

      - name: Publish test report
        uses: mikepenz/action-junit-report@ee6b445351cd81e2f73a16a0e52d598aeac2197f # tag=v5.3.0
        if: always()
        with:
          report_paths: build/test-results/unit.xml

      - name: Publish coverage report
        uses: 5monkeys/cobertura-action@ee5787cc56634acddedc51f21c7947985531e6eb # tag=v14
        with:
          path: coverage/cobertura-coverage.xml
          minimum_coverage: 100
          fail_below_threshold: true
