name: 'Jest'

on: [push, pull_request]

permissions: read-all

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Setup node
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          node-version: 16

      - name: Run tests
        run: |
          npm ci
          npx lerna run prepack
          npm run test-ci
        env:
          TZ: America/Toronto

      - name: Publish test report
        uses: mikepenz/action-junit-report@ab07dd7abefd456d92ecbeb22f81392fafe3d528 # tag=v3.5.0
        if: always()
        with:
          report_paths: build/test-results/unit.xml

      - name: Publish coverage report
        uses: 5monkeys/cobertura-action@4157521550018abbbd29dfdf1b5963e907ea37f0 # tag=v13
        with:
          path: coverage/cobertura-coverage.xml
          minimum_coverage: 100
          fail_below_threshold: true
