name: "Jest"

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Run tests
      run: |
        npm ci
        npx lerna run prepack
        npm run test-ci
      env:
        TZ: America/Toronto

    - name: Publish test report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: 'build/test-results/unit.xml'

    - name: Publish coverage report
      uses: 5monkeys/cobertura-action@v13
      with:
        path: coverage/cobertura-coverage.xml
        minimum_coverage: 100
        fail_below_threshold: true
